unit Unit1;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, StdCtrls, planswift9_tlb,AutoCAD_TLB;

type
  TForm1 = class(TForm)
    PageCBX: TComboBox;
    Button1: TButton;
    Button2: TButton;
    Label1: TLabel;
    Processtxt: TMemo;
    procedure FormCreate(Sender: TObject);
    procedure Button1Click(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form1: TForm1;
  ps:IPlanswift;
   pglst: TStringList;
  slst: TStringList;
  ACad: IACadApplication;
  AMS: IAcadModelSpace;
implementation

{$R *.dfm}
uses
comobj;

Procedure populateitemList(itm:IItem; lst:TStringlist; itmType:String);
var
  idx: Integer;
  citm: IItem;
  isItm: Boolean;
begin
  for idx := 0 to itm.ChildCount  - 1 do begin
    citm := itm[idx];
    if citm.GetProperty('Type').ResultAsString = 'Folder' then begin
      //(recursive) if item is a folder load all its childPages
      PopulateItemList(citm,lst,itmType);
    end else begin
       isItm := citm.GetPropertyResultAsBoolean(itmType,false);
       if isItm then
        lst.Add(citm.GUID);

       //(recursive)if this item has child items we will want to include those as well
       if citm.ChildCount > 0 then
        populateItemList(citm, lst, itmType);
    end;

  end;
end;

procedure GetpageSections(pg:String; lst:TStringList);
var
  idx: Integer;
  itm: IItem;
begin
  for idx := 0 to slst.Count - 1 do begin
    itm := ps.GetItem(slst.Strings[idx]);
    if itm.GetPropertyResultAsString('PageGUID','') = pg then
      lst.Add(itm.GUID);
  end;
end;
procedure itemToAcad(itm:IItem);
var
  idx: Integer;

  SX: Extended;
  SY: Extended;
  aptx: Double;
  apty: Double;
  isclosed: Boolean;

  thisline: IAcadLWPolyline;
  pt: IPoint;
  pline: IAcadPolyline;
  ary: olevariant;
begin
  form1.Processtxt.Text := form1.Processtxt.Text + 'Exporting Item: ' + itm.Name + #13#10;
  SX := ps.GetItem(itm.GetProperty('PageGUID').ResultAsString).GetProperty('ScaleX').ResultAsFloat;
  SY := ps.GetItem(itm.GetProperty('PageGUID').ResultAsString).GetProperty('ScaleY').ResultAsFloat;

   thisline := AMS.AddLightWeightPolyline(vararraycreate([0],varDouble));
   thisline.color := acGreen;
  for idx := 0 to itm.PointCount - 1 do begin
      pt := itm.GetPoint(idx);
      aptx := (pt.X / sx) * 12;
      apty := - (pt.Y/sy) * 12;
      ary := vararraycreate([0, 1], varDouble);
      ary[0] := aptx;
      ary[1] := apty;
      thisLine.AddVertex(idx,ary);
  end;


end;
procedure TForm1.Button1Click(Sender: TObject);
var
  pg: string;
  pgSlst: TStringList;
  idx: Integer;
  Adoc: IAcadDocument;
begin
pgSlst := TStringList.Create;
pg := pglst.Strings[pagecbx.itemIndex];

//Populate Page Sections
GetpageSections(pg,pgSLst);
if pgSlst.Count = 0 then begin
  ShowMessage('Could Not Find Any Sections on Page: Please Select a Different Page');
  PageCBX.SetFocus;
  Exit;
end;
 try
  //Load Autoocad if Not already open
  Acad := CoAcadApplication.Create;
  //Acad := GetActiveOleObject('AutoCad.Application') as AcadApplication;
  Acad.Visible := true;
  Adoc := Acad.ActiveDocument;
  AMS := Adoc.ModelSpace;
  for idx  := 0 to pgslst.count - 1 do
    itemToAcad(ps.GetItem(pgslst.Strings[idx]))
 finally
   pgSlst.Free;
   Acad := nil;
   ADoc := nil;
   AMS := nil;
 end;
end;

procedure TForm1.FormCreate(Sender: TObject);
var
  pgPath: WideString;
  tkPath: WideString;
  pgsItem: IItem;
  sItem: IItem;
  idx: Integer;


begin
  //Load Planswift if not already open
  ps := coPlanswift.Create;
  pgPath := ps.Root.FullPath + '\Job\Pages';
  tkPath := ps.Root.FullPath + '\Job\TakeOff';
  //get Items
  pgsItem := ps.GetItem(pgPath);
  sItem := ps.GetItem(tkpath);
  //Create Page and takeoff list
  pglst := TstringList.Create;
  slst := TStringList.Create;
  // load Pages into List
  PopulateItemList(pgsitem,pgLst,'IsPage');
  // load Sections into list
  PopulateItemList(SItem,slst,'IsSection');
  // Load Pages into combobox
  for idx := 0 to pglst.count - 1 do
    pagecbx.Items.Add(ps.GetItem(pglst.Strings[idx]).Name);
end;

end.
